---
# Install nginx to serve static files and
# proxy all requests to a local WSGI application server

- name: Enable nginx repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum: name={{ item }} state=present
  with_items:
   - nginx

- name: Insert iptables rule for nginx
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j ACCEPT"
  notify: restart iptables

- name: Start nginx at boot time
  service: name=nginx enabled=yes

- name: Increase server names hash size
  lineinfile: dest=/etc/nginx/nginx.conf create=yes state=present insertafter="http \{"
              line="    server_names_hash_bucket_size {{ server_names_hash_bucket_size }};"
  notify: restart nginx
