---

- name: Enable nginx repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx and pals
  yum: name={{ item }} state=present
  with_items:
   - nginx

- name: Insert iptables rule for nginx
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j ACCEPT"
  notify: restart iptables

- name: Start nginx at boot time
  service: name=nginx state=started enabled=yes

- name: Create application user and ssh keys
  user: name={{ user_name }} password={{ user_pass }} generate_ssh_key=yes

- name: Create public directory to serve static files
  file: path=/home/{{ user_name }}/public owner={{ user_name }} group={{ user_name }} mode=0755 state=directory

- name: Make user's home dir xecutable  
  file: path=/home/{{ user_name }} mode=0755 state=directory

- name: Copy 500 default templates
  copy: src=500.html dest=/home/{{ user_name }}/public owner={{ user_name }} group={{ user_name }}

- name: Copy 404 default templates
  copy: src=404.html dest=/home/{{ user_name }}/public owner={{ user_name }} group={{ user_name }}

- name: Increase server names hash size
  lineinfile: dest=/etc/nginx/nginx.conf create=yes state=present insertafter="http \{"
              line="    server_names_hash_bucket_size {{ server_names_hash_bucket_size }};"
  notify: restart iptables

- name: Create a proxy host
  template: src=proxy.conf.j2 dest=/etc/nginx/conf.d/{{ app_name }}.conf owner=root group=root mode=0644
  notify: restart nginx