---
# ^^^ YAML documents must begin with the document separator "---"

# Overview: Playbook to bootstrap a new host for serving Django apps

- name: Prepare a node for basic functions
  hosts: all
  tags: basic

  roles:
    - common
    - python

- name: configure http server
  hosts: appservers

  roles:
    - nginx

- name: install gunicorn on a virtualenv
  hosts: appservers
  sudo: True
  sudo_user: "{{ user_name }}"

  roles:
    - gunicorn

- name: install redis
  hosts: appservers

  roles:
    - redis

- name: configure and deploy dbservers
  hosts: dbservers

  roles:
    - postgres

- name: configure supervisor
  hosts: appservers
  sudo: True
  sudo_user: "{{ user_name }}"

  roles:
    - supervisor
