---
# ^^^ YAML documents must begin with the document separator "---"


###
# Playbook start
#
# Overview: Playbook to bootstrap a new host for serving Django apps
# Description: 
#   TODO
- 

  ###
  # hosts is a param so we can invoke the playbook on different machines
  hosts: {{	target }}
  remote_user: root
  sudo: True

  tasks:
    - include: common/tasks/system.yml tags=system
    - include: common/tasks/postgresql.yml tags=postgresql

  handlers:
    ##
    # common handlers are defined in the following file
    - include: common/handlers/main.yml