---
# ^^^ YAML documents must begin with the document separator "---"

# Overview: Playbook to bootstrap a new host for serving Django apps

- name: Prepare a node for basic functions
  hosts: all
  tags: basic

  roles:
    - common
    - python

- name: Add service nginx
  hosts: appservers
  tags: nginx

  roles:
    - nginx

- name: Add service redis
  hosts: all
  tags: redis

  roles:
    - redis

- name: Add service postgresql
  hosts: all
  tags: postgres

  roles:
    - postgres

- name: install gunicorn on a virtualenv
  hosts: all
  sudo: True
  sudo_user: "{{ user_name }}"

  roles:
    - gunicorn

- name: configure supervisor
  hosts: all
  sudo: True
  sudo_user: "{{ user_name }}"

  roles:
    - supervisor
