---
# ^^^ YAML documents must begin with the document separator "---"

# Overview: Playbook to bootstrap a new host for serving Django apps

- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - common

- name: install Python on webservers
  hosts: appservers
  user: root

  roles:
    - python

- name: configure http server
  hosts: appservers
  user: root

  roles:
    - nginx

- name: install gunicorn on a virtualenv
  hosts: appservers
  user: {{ user_name }}
  sudo: False

  roles:
    - gunicorn

- name: configure and deploy dbservers
  hosts: dbservers
  user: root

  roles:
    - postgres
