---

# Overview: Bootstrap a new node, ready to server Django applications

- name: Prepare a node for some basic functions
  hosts: all
  tags: basic

  roles:
    - common
    - python

- name: Add nginx service
  hosts: appservers
  tags: nginx

  roles:
    - nginx

- name: Add redis service
  hosts: all
  tags: redis

  roles:
    - redis

- name: Add postgresql service
  hosts: all
  tags: postgres

  roles:
    - postgres

- name: Prepare for application deployment
  hosts: all
  tags: application

  sudo: True
  sudo_user: "{{ user_name }}"

  roles:
    - application
    - supervisor
    - gunicorn
