---
# Task for setting up Python and relative dev tools
# we need these to support PythonZ installations

- name: Install Python dependency libraries
  yum: pkg="{{item}}" state=present
  with_items:
    - curl
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel
    - libjpeg-devel

- name: Configuring Python pip
  shell:
    executable=/bin/bash
    curl https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py | python2.7 -

- name: Install virtualenv and the wrapper
  pip: name=virtualenvwrapper

- name: Setup virtualenv and the wrapper
  copy: src=virtualenvwrapper.sh dest=/etc/profile.d/virtualenvwrapper.sh

- name: Install PythonZ
  shell:
    executable=/bin/bash
    curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install
