---
# Task for setting up Python and relative dev tools
# we need these to support PythonZ installations

- name: Install Python dependency libraries
  yum: pkg="{{item}}" state=present
  with_items:
    - curl
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel
    - libjpeg-devel
    - python-pip

- name: Install virtualenv and the wrapper
  pip: name=virtualenvwrapper

- name: Setup virtualenv and the wrapper
  copy: src=virtualenvwrapper.sh dest=/etc/profile.d/virtualenvwrapper.sh

# Python is installed globally so if this machine has 7 running apps, they can
# share the same python interpreter

- name: Install PythonZ
  shell: curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
