---
# Task for setting up Python and relative dev tools

# we need these to support PythonZ installations
- name: Install Python dependency libraries
  yum: pkg="{{item}}" state=present
  with_items:
    - curl
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel
    - libjpeg-devel
    - python-virtualenvwrapper

- name: Setup virtualenv and the wrapper
  copy: src=virtualenvwrapper.sh dest=/etc/profile.d/virtualenvwrapper.sh

- name: Install PythonZ
  action: curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
  user: {{ user_name }}
  sudo: False

- name: Install CPython
  action: pythonz install {{ python_version }}
  user: {{ user_name }}
  sudo: False