---
# This playbook contains common plays that will be run on all nodes.

- name: Installing dependencies and support tools
  yum: name={{item}} state=latest
  with_items:
    - libselinux-python
    - vim

- name: Create the EPEL Repository.
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Updating to latest kernel
  yum: name={{item}} state=latest
  register: kernel
  with_items:
    - kernel
    - kernel-firmware

- name: Update system
  yum: name=* state=latest

# TODO: be sure SELinux is running and configure it properly
- name: disable SELinux
  selinux: state=disabled

- name: Rebooting server if kernel has changed
  command: /sbin/reboot
  when: kernel|changed

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30

- name: Install development tools
  yum: name="@Development tools" state=present

- name: Deploy basic iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables

#- name: Test to see if selinux is running
#  command: getenforce
#  register: sestatus
#  changed_when: false
