---
# Contains common plays that must be run at least once

- name: Installing dependencies and support tools
  yum: name={{item}} state=latest
  with_items:
    - iptables-services
    - libselinux-python
    - vim

- name: Adding EPEL Repository
  yum: name=epel-release state=latest

- name: Updating to latest kernel
  yum: name={{item}} state=latest
  register: kernel
  with_items:
    - kernel
    - kernel-firmware

- name: Update system
  yum: name=* state=latest

# TODO: be sure SELinux is running and configure it properly
- name: disable SELinux
  selinux: state=disabled

- name: Rebooting server
  command: shutdown -r now "Ansible kernel changed trigger"
  async: 0
  poll: 0
  ignore_errors: true
  when: kernel|changed

- name: Waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10

- name: Install development tools
  yum: name="@Development tools" state=present

- name: Deploy basic iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables

#- name: Test to see if selinux is running
#  command: getenforce
#  register: sestatus
#  changed_when: false
