---
# This playbook contains common plays that will be run on all nodes.

- name: Installing dependencies
  yum: name=libselinux-python state=latest

- name: Update system
  yum: name=* state=latest

# TODO: be sure SELinux is running and configure it properly

- name: disable SELinux
  selinux: state=disabled

- name: Reboot the server
  command: /sbin/reboot

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30

- name: Install development tools
  yum: name="@Development tools" state=present

- name: Deploy basic iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables

#- name: Test to see if selinux is running
#  command: getenforce
#  register: sestatus
#  changed_when: false
