---
# Prepare all components to host WSGI application

# Generic configurations

- name: Create public directory to serve static files
  file: path=/home/{{ user_name }}/public owner={{ user_name }} group={{ user_name }} mode=0755 state=directory

- name: Make user's home dir executable
  file: path=/home/{{ user_name }} mode=0755 state=directory

- name: Copy html default templates
  copy: src={{item}} dest=/home/{{ user_name }}/public owner={{ user_name }} group={{ user_name }}
  with_items:
    - 500.html
    - 404.html

- name: Create virtualenv
  shell:
    executable=/bin/bash
    source `which virtualenvwrapper.sh` && mkvirtualenv -p {{ python_path.stdout }} {{ app_name }}

# postgresql configurations

- name: Create a new postgres user
  postgresql_user: name={{ user_name }} password={{ user_pass }}
  sudo: True
  sudo_user: postgres
  when: createdb == True

- name: Create a new database and grant privileges
  postgresql_db: name={{ app_name }} owner={{ user_name }}
  sudo: True
  sudo_user: postgres
  when: createdb == True
