---
# Prepare all component to host WSGI application

# Generic configurations

- name: Create application user and ssh keys
  user: name={{ user_name }} password={{ user_pass }} generate_ssh_key=yes

- name: Create public directory to serve static files
  file: path=/home/{{ user_name }}/public owner={{ user_name }} group={{ user_name }} mode=0755 state=directory

- name: Make user's home dir xecutable
  file: path=/home/{{ user_name }} mode=0755 state=directory

- name: Copy 500 default templates
  copy: src=500.html dest=/home/{{ user_name }}/public owner={{ user_name }} group={{ user_name }}

- name: Copy 404 default templates
  copy: src=404.html dest=/home/{{ user_name }}/public owner={{ user_name }} group={{ user_name }}

# nginx configurations

- name: Create a proxy host
  template: src=proxy.conf.j2 dest=/etc/nginx/conf.d/{{ app_name }}.conf owner=root group=root mode=0644
  notify: restart nginx

# check or install a new python interpreter

- name: Install or use chosen CPython
  command: pythonz install "{{ python_version }}"
