---
# Postgresql server configuration

- name: Disabling old Postgresql repository
  lineinfile: dest=/etc/yum.repos.d/CentOS-Base.repo state=present
              insertafter="{{ item.insertafter }}"
              line="{{ item.line }}"
  with_items:
    - { insertafter: '^\[base\]$', line: 'exclude=postgresql* # Disable postgres for base' }
    - { insertafter: '^\[updates\]$', line: 'exclude=postgresql* # Disable postgres for updates' }

- name: Enabling Postgresql 9.3 repository [Download]
  get_url: url=http://yum.postgresql.org/9.3/redhat/rhel-6-x86_64/pgdg-centos93-9.3-1.noarch.rpm dest=/tmp/pgdg-centos93-9.3-1.noarch.rpm

- name: Enabling Postgresql 9.3 repository [Install]
  yum: name=/tmp/pgdg-centos93-9.3-1.noarch.rpm state=present

- name: Installing postgresql server
  yum: pkg={{item}} state=present
  with_items:
    - postgresql93-server
    - postgresql93-devel
    - python-psycopg2

- name: Database initialization
  shell:
    executable=/bin/bash
    creates=/var/lib/pgsql/9.3/data/pg_hba.conf
    /usr/pgsql-9.3/bin/postgresql93-setup initdb

- name: Starting postgresql service
  service: name=postgresql-9.3 state=started

- name: Starting postgresql on boot
  service: name=postgresql-9.3 enabled=yes

- name: Configuring postgres user
  ignore_errors: yes
  postgresql_user: user=postgres password={{ psql_pass }} state=present
  sudo: True
  sudo_user: postgres
  notify: restart postgres

- name: Copying default configuration files
  copy: src=pg_hba.conf dest=/var/lib/pgsql/9.3/data/pg_hba.conf owner=postgres group=postgres mode=0600 backup=yes
  notify: restart postgres

- name: Add bin folder to env $PATH
  copy: src=postgresql.sh dest=/etc/profile.d/postgresql.sh

- name: Insert iptables rule for postgres
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="5432" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport 5432 -j ACCEPT"
  notify: restart iptables
