---
# Configuration of postgresql server

- name: Installing postgresql server
  yum: pkg={{item}} state=present
  with_items:
    - postgresql-server
    - postgresql-devel
    - python-psycopg2

- name: Database initialization
  command: service postgresql initdb creates=/var/lib/pgsql/data/pg_hba.conf

- name: Starting postgresql service
  action: service name=postgresql state=started

- name: Starting postgresql on boot
  service: name=postgresql enabled=yes

- name: Configuring postgres user
  ignore_errors: yes
  postgresql_user: user=postgres password={{ psql_pass }} state=present
  sudo: True
  sudo_user: postgres
  notify: restart postgres

- name: Copying default configuration files
  copy: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf owner=postgres group=postgres mode=0600 backup=yes
  notify: restart postgres

- name: Insert iptables rule for nginx
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport 5432 -j ACCEPT"
  notify: restart iptables